name: "Regex Match Checker"
description: "Checks if a regex matches and if it does you can configure if you want the action to fail or succeed"
inputs:
  text:
    description: "The text you want to check"
    required: true
  regex:
    description: "The regex you want to use for checking"
    required: true
  flags:
    description: "The regex flags you want to use for checking"
    required: false
    default: "g"
  fail-on-match:
    description: "Whether to fail on successful match"
    required: false
    default: false
  fail-on-no-match:
    description: "Whether to fail on no match"
    required: false
    default: true
outputs:
  match:
    description: "Whether the regex matched or not"
runs:
  using: "node20"
  main: "dist/index.js"
